const GET_ALL_CARGOS = `SELECT * FROM ICTDAT.ZAY`;
const GET_ALL_OFFSET = `SELECT * FROM ICTDAT.ZAY
OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY`;

module.exports = {
  GET_ALL_CARGOS,
  GET_ALL_OFFSET,
};
